version: '3.8'

services:
  # 1. PostgreSQL (replaces AWS RDS)
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432" # Expose PG port to your local machine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=subercraftex
      - POSTGRES_PASSWORD=localdevpassword
      - POSTGRES_DB=subercraftex_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U subercraftex -d subercraftex_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Redis (replaces AWS ElastiCache)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379" # Expose Redis port
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 3. MinIO (replaces AWS S3)
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"  # API Port
      - "9001:9001"  # Console UI Port
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 2s
      retries: 5

  # 4. Elasticsearch (replaces AWS OpenSearch/Elasticsearch Service)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Disable security for easy local dev
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Limit memory usage

volumes:
  postgres_data:
  minio_data:
