version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend  # Ensure this path is correct
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend  # Ensure this path is correct
    ports:
      - "4000:4000"
    volumes:
      - ../backend:/app
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/pesEcomerceDB
       - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
     

  mongo:
    image: mongo
    ports:
      - "27017:27017"
